services:
  web:
    build: .
    container_name: library_web
    ports:
      - "5000:8080"
    depends_on:
      - db
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=db;Database=LibraryManagementSystemDb;User Id=sa;Password=YourStrong@Pass123;TrustServerCertificate=True;

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: library_sql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong@Pass123
    ports:
      - "1433:1433"
    volumes:
      - library_sql_data:/var/opt/mssql

volumes:
  library_sql_data: